# Generated by Django 3.0.6 on 2021-01-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(null=True, upload_to='media/pdf')),
                ('output_file', models.FileField(null=True, upload_to='media/audio')),
            ],
        ),
    ]
