# Generated by Django 3.0.6 on 2021-01-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookify',
            name='input_file',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='bookify',
            name='output_file',
            field=models.FileField(null=True, upload_to='audio'),
        ),
    ]
